# -*- coding: utf-8 -*-
"""Deteccao_Borda_Canny_Edge

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UJsAYGBHzH8ykzhA-zCHUGd8eo5-_P3E
"""

import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt

img = cv.imread("/content/Leao.jpg")
img = cv.cvtColor(img, cv.COLOR_BGR2RGB)
plt.imshow(img)

edges = cv.Canny(img,100,200)

plt.imshow(edges)

plt.subplot(121),plt.imshow(img,cmap = 'gray')
plt.title('Imagem Original'), plt.xticks([]), plt.yticks([])
plt.subplot(122),plt.imshow(edges,cmap = 'gray')
plt.title('Bordas'), plt.xticks([]), plt.yticks([])
plt.show()