# -*- coding: utf-8 -*-
"""Gradientes_Imagem

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DLwZsQkpJuCwLeXz9YUv6GGCFqrSCHaN
"""

import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt

img = cv.imread("/content/Leao.jpg")
img = cv.cvtColor(img, cv.COLOR_BGR2RGB)
plt.imshow(img)

laplacian = cv.Laplacian (img, cv.CV_64F)
sobelx = cv.Sobel (img, cv.CV_64F, 1,0, ksize = 5)
sobely = cv.Sobel (img, cv.CV_64F, 0,1, ksize = 5)

plt.title("Laplace")
plt.imshow(laplacian, cmap='gray')

plt.title("Sobel X")
plt.imshow(sobelx, cmap='gray')

plt.title("Sobel Y")
plt.imshow(sobely, cmap='gray')