# -*- coding: utf-8 -*-
"""Misturando_Imagens_OpenCV

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lkW87MAepuDBXnqNLWyIT--QX5SPJ6iD
"""

import cv2 as cv
import matplotlib.pyplot as plt
import numpy as np

img1 = cv.imread("/content/Leao.jpg")
img1 = cv.cvtColor(img1, cv.COLOR_BGR2RGB)
img2 = cv.imread("/content/watermark_no_copy.png")
img2 = cv.cvtColor(img2, cv.COLOR_BGR2RGB)

plt.imshow(img1)

img1.shape

img2.shape

#Misturando imagens do mesmo tamanho
img1 = cv.resize(img1,(1000, 600))
img2 = cv.resize(img2,(1000, 600))

plt.imshow(img1)

blended = cv.addWeighted(src1=img1, alpha=0.7, src2=img2,
                         beta=0.2, gamma=0)

plt.imshow(blended)

