# -*- coding: utf-8 -*-
"""Quantizacao_Cores_OpenCV

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Zjot4zcG7ZYw1ue7zGDSHpniEe8Lhrl
"""

import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt

img = cv.imread("/content/Tony-Stark.jpg")
img = cv.cvtColor(img, cv.COLOR_BGR2RGB)
plt.imshow(img)

z = img.reshape((-1,3))

z = np.float32(z)

criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 10, 1.0)
K = 8
ret, label ,center=cv.kmeans(z, K, None, criteria, 10, cv.KMEANS_RANDOM_CENTERS)

center = np.uint8(center)
res = center[label.flatten()]
res2 = res.reshape((img.shape))

plt.title("Imagem Final")
plt.imshow(res2)